In [175]:
import pandas as pd
from pathlib import Path

In [176]:
file_path = ".\Resources\cleaned-county-to-county-2015-2019-ins-outs-nets-gross.csv"
cleaned_county_df = pd.read_csv(file_path)
cleaned_county_df.rename(columns = {"State and County of Geography A":"State and County name"}, inplace = True)
cleaned_county_df.rename(columns = {"Net Migration from Geography B to Geography A1":"Net_Migration_from_Geography_B_to_Geography_A1"}, inplace = True)
cleaned_county_df.head()

,State Code of Geography A,FIPS County Code of Geography A,State/U.S. Island Area/Foreign Region Code of Geography B,FIPS County Code of Geography B,State Name of Geography A,County Name of Geography A,State and County name,State/U.S. Island Area/Foreign Region of Geography B,County Name of Geography B,State and County of Geography B,Flow from Geography B to Geography A,Counterflow from Geography A to Geography B1,Net_Migration_from_Geography_B_to_Geography_A1,Gross Migration between Geography A and Geography B1
0,1,1,001,3.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Baldwin County,"Baldwin County, Alabama",25,448,-423,473
1,1,1,001,5.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Barbour County,"Barbour County, Alabama",4,0,4,4
2,1,1,001,7.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Bibb County,"Bibb County, Alabama",10,34,-24,44
3,1,1,001,9.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Blount County,"Blount County, Alabama",3,0,3,3
4,1,1,001,15.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Calhoun County,"Calhoun County, Alabama",2,42,-40,44

In [177]:
file_path = ".\Resources\County_population_totals_2010_2019_co-est2019-alldata.csv"
total_county_df = pd.read_csv(file_path)
total_county_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,State and County name,CENSUS2010POP,ESTIMATESBASE2010,...,RDOMESTICMIG2019,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019
0,40,3,6,1,0,Alabama,Alabama,"Alabama, Alabama",4779736,4780125,...,1.917501,0.578434,1.186314,1.522549,0.563489,0.626357,0.745172,1.090366,1.773786,2.483744
1,50,3,6,1,1,Alabama,Autauga County,"Autauga County, Alabama",54571,54597,...,4.847310,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
2,50,3,6,1,3,Alabama,Baldwin County,"Baldwin County, Alabama",182265,182265,...,24.017829,16.641870,17.488579,22.751474,20.184334,17.725964,21.279291,22.398256,24.727215,24.380567
3,50,3,6,1,5,Alabama,Barbour County,"Barbour County, Alabama",27457,27455,...,-5.690302,0.292676,-6.897817,-8.132185,-5.140431,-15.724575,-18.238016,-24.998528,-8.754922,-5.165664
4,50,3,6,1,7,Alabama,Bibb County,"Bibb County, Alabama",22915,22915,...,1.385134,-4.998356,-3.787545,-5.797999,1.331144,1.329817,-0.708717,-3.234669,-6.857092,1.831952

In [178]:
joined_df=pd.merge(cleaned_county_df,total_county_df,on="State and County name")
joined_df.head()

,State Code of Geography A,FIPS County Code of Geography A,State/U.S. Island Area/Foreign Region Code of Geography B,FIPS County Code of Geography B,State Name of Geography A,County Name of Geography A,State and County name,State/U.S. Island Area/Foreign Region of Geography B,County Name of Geography B,State and County of Geography B,...,RDOMESTICMIG2019,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016,RNETMIG2017,RNETMIG2018,RNETMIG2019
0,1,1,001,3.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Baldwin County,"Baldwin County, Alabama",...,4.84731,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
1,1,1,001,5.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Barbour County,"Barbour County, Alabama",...,4.84731,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
2,1,1,001,7.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Bibb County,"Bibb County, Alabama",...,4.84731,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
3,1,1,001,9.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Blount County,"Blount County, Alabama",...,4.84731,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062
4,1,1,001,15.0,Alabama,Autauga County,"Autauga County, Alabama",Alabama,Calhoun County,"Calhoun County, Alabama",...,4.84731,6.018182,-6.226119,-3.902226,1.970443,-1.712875,4.777171,0.849656,0.540916,4.560062

In [179]:
table_df=joined_df[["State and County name", "State/U.S. Island Area/Foreign Region of Geography B",
                         "Net_Migration_from_Geography_B_to_Geography_A1",
                        "POPESTIMATE2015"]]
table_df.head()

,State and County name,State/U.S. Island Area/Foreign Region of Geography B,Net_Migration_from_Geography_B_to_Geography_A1,POPESTIMATE2015
0,"Autauga County, Alabama",Alabama,-423,54864
1,"Autauga County, Alabama",Alabama,4,54864
2,"Autauga County, Alabama",Alabama,-24,54864
3,"Autauga County, Alabama",Alabama,3,54864
4,"Autauga County, Alabama",Alabama,-40,54864

In [180]:
table_df['Net_Migration_from_Geography_B_to_Geography_A1'] = table_df['Net_Migration_from_Geography_B_to_Geography_A1'].fillna(0)

C:\Users\John\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [181]:
#table_df.to_csv (".\Resources\merge_pop_dataframe.csv", index=True, header=True)

In [182]:
table_df.dtypes

State and County name                                   object
State/U.S. Island Area/Foreign Region of Geography B    object
Net_Migration_from_Geography_B_to_Geography_A1          object
POPESTIMATE2015                                          int64
dtype: object

In [183]:
table_df['Net_Migration_from_Geography_B_to_Geography_A1']=pd.to_numeric(table_df['Net_Migration_from_Geography_B_to_Geography_A1'], errors='coerce').fillna(0).astype(int)

C:\Users\John\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [184]:
table_df.dtypes

State and County name                                   object
State/U.S. Island Area/Foreign Region of Geography B    object
Net_Migration_from_Geography_B_to_Geography_A1           int32
POPESTIMATE2015                                          int64
dtype: object

In [185]:
table_df["Percent_Change_in_Pop"]=table_df["Net_Migration_from_Geography_B_to_Geography_A1"]/table_df["POPESTIMATE2015"]
table_df

C:\Users\John\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,State and County name,State/U.S. Island Area/Foreign Region of Geography B,Net_Migration_from_Geography_B_to_Geography_A1,POPESTIMATE2015,Percent_Change_in_Pop
0,"Autauga County, Alabama",Alabama,-423,54864,-0.007710
1,"Autauga County, Alabama",Alabama,4,54864,0.000073
2,"Autauga County, Alabama",Alabama,-24,54864,-0.000437
3,"Autauga County, Alabama",Alabama,3,54864,0.000055
4,"Autauga County, Alabama",Alabama,-40,54864,-0.000729
...,...,...,...,...,...
432795,"Weston County, Wyoming",Wyoming,-8,7208,-0.001110
432796,"Weston County, Wyoming",Wyoming,2,7208,0.000277
432797,"Weston County, Wyoming",Wyoming,12,7208,0.001665
432798,"Weston County, Wyoming",Wyoming,6,7208,0.000832
432799,"Weston County, Wyoming",Wyoming,-2,7208,-0.000277

In [186]:
pivot_table = pd.pivot_table(table_df, index=["State and County name","State/U.S. Island Area/Foreign Region of Geography B"], 
                        values=["Net_Migration_from_Geography_B_to_Geography_A1","POPESTIMATE2015","Percent_Change_in_Pop"])
pivot_table

                                                                                     Net_Migration_from_Geography_B_to_Geography_A1  \
State and County name            State/U.S. Island Area/Foreign Region of Geogra...
Abbeville County, South Carolina California                                                                               -7.000000
                                 District of Columbia                                                                      4.000000
                                 Europe                                                                                    0.000000
                                 Florida                                                                                  -0.666667
                                 Georgia                                                                                  20.666667
...                                                                                                                             ...
Ziebach County, South Dakota     New Jersey                                                                                6.000000
                                 North Dakota                                                                             -5.000000
                                 South Dakota                                                                             -6.533333
                                 Texas                                                                                   -18.000000
                                 Wyoming                                                                                  -4.000000

                                                                                     POPESTIMATE2015  \
State and County name            State/U.S. Island Area/Foreign Region of Geogra...
Abbeville County, South Carolina California                                                    24796
                                 District of Columbia                                          24796
                                 Europe                                                        24796
                                 Florida                                                       24796
                                 Georgia                                                       24796
...                                                                                              ...
Ziebach County, South Dakota     New Jersey                                                     2837
                                 North Dakota                                                   2837
                                 South Dakota                                                   2837
                                 Texas                                                          2837
                                 Wyoming                                                        2837

                                                                                     Percent_Change_in_Pop
State and County name            State/U.S. Island Area/Foreign Region of Geogra...
Abbeville County, South Carolina California                                                      -0.000282
                                 District of Columbia                                             0.000161
                                 Europe                                                           0.000000
                                 Florida                                                         -0.000027
                                 Georgia                                                          0.000833
...                                                                                                    ...
Ziebach County, South Dakota     New Jersey                                                       0.002115
                                 North Dakota                                                    -0.001762
                                 South Dakota                                                    -0.002303
                                 Texas                                                           -0.006345
                                 Wyoming                                                         -0.001410

[83434 rows x 3 columns]